### ISSUE TITLE
Проблема с updateOnPreview у полей из BelongsToMany

### ISSUE THREAD

**Issue by Victor-Fyodorov** [moonshine-software/moonshine#823]
### MoonShine Version

2.7.5

### Laravel Version

10.45.1

### PHP Version

8.2.14

### Database Driver & Version

mysql/mysql-server:8.0

### Description

Доброго дня!

При поптыке сделать таблицу с полями из BelongsToMany с pivot полями типа Switcher и updateOnPreview(), возникла проблема при редактировании значения свитчера через таблицу

<img width="1125" alt="Снимок экрана 2024-02-23 в 11 18 23" src="https://github.com/moonshine-software/moonshine/assets/161011902/b1e53568-b5ce-462f-933f-60fd7470ba6f">

Код ресурса:

```
<?php

declare(strict_types=1);

namespace App\MoonShine\Resources;

use Illuminate\Database\Eloquent\Model;
use App\Models\TournamentTeam;

use MoonShine\Decorations\Column;
use MoonShine\Decorations\Grid;
use MoonShine\Fields\Number;
use MoonShine\Fields\Relationships\BelongsTo;
use MoonShine\Fields\Relationships\BelongsToMany;
use MoonShine\Fields\Switcher;
use MoonShine\Fields\Text;
use MoonShine\Resources\ModelResource;
use MoonShine\Decorations\Block;
use MoonShine\Fields\ID;

/**
 * @extends ModelResource<TournamentTeam>
 */
class TournamentTeamResource extends ModelResource
{
    protected string $model = TournamentTeam::class;

    protected string $title = 'TournamentTeams';

    protected string $column = 'title';

    public function fields(): array
    {
        return [
            Grid::make([
                Column::make([
                    ID::make()->sortable(),
                    Text::make('Наименование команды', 'team_title')->required(),
                    Number::make('Номер состава', 'team_number'),
                    BelongsTo::make('Турнир', 'tournament', resource: new TournamentResource())
                        ->searchable(),
                ]),
                Column::make([
                    BelongsToMany::make('Участники', 'users', resource: new UserResource())
                        ->fields([
                            Switcher::make('Подтвержден', 'approved')->updateOnPreview(),
                        ])
                        ->searchable(),
                ])
            ])
        ];
    }

    public function filters(): array
    {
        return [
            BelongsTo::make('Турнир', 'tournament', resource: new TournamentResource())->searchable(),
//            Switcher::make('Подтвержден', 'confirmed')->nullable(),
        ];
    }

    public function rules(Model $item): array
    {
        return [];
    }
}
```

Код модели:

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use MoonShine\Fields\Relationships\BelongsToMany;

class TournamentTeam extends Model
{
    use HasFactory;

    protected $guarded = [];

    public static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->title = $model->team_title . (
                $model->team_number ?
                    ' (Состав ' . $model->team_number . ')' :
                    ''
                );
        });
    }

    /**
     * Get the tournament.
     */
    public function tournament(): BelongsTo
    {
        return $this->belongsTo(Tournament::class, 'tournament_id');
    }

    public function users(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(
            User::class,
            'tournament_team_partisipants',
            'tournament_team_id',
            'user_id'
        )->withPivot('approved');
    }
}
```
Запускаю все через Laravel Sail. В чем моджет быть проблема?

### Steps To Reproduce

Установлен laravel sail:

```
services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - meilisearch
            - mailpit
            - selenium
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://localhost:7700/health'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    selenium:
        image: selenium/standalone-chrome
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:mysql
        ports:
            - 8087:80
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: mysql
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
```

Установлен Breeze с React и Inertia Для Users
